# Generated by Django 3.0 on 2024-07-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
    ]
