name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Triggers on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: |
        IMAGE_NAME=shmuel505/oc-lettings
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker build -t $IMAGE_NAME:$COMMIT_HASH .
        docker tag $IMAGE_NAME:$COMMIT_HASH $IMAGE_NAME:latest

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=shmuel505/oc-lettings
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker push $IMAGE_NAME:$COMMIT_HASH
        docker push $IMAGE_NAME:latest