name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Create env file
      run: |
        touch oc_lettings_site/.env
        echo SECRET_KEY=${SECRET_KEY} >> oc_lettings_site/.env
        echo ENV_SENTRY=${ENV_SENTRY}  >> oc_lettings_site/.env
        echo SENTRY_KEY=${SENTRY_KEY}  >> oc_lettings_site/.env
        cat oc_lettings_site/.env
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENV_SENTRY: ${{ secrets.ENV_SENTRY }}
        SENTRY_KEY: ${{ secrets.SENTRY_KEY }}


    - name: Analysing the code with flake8
      run: |
        flake8

    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report
